from .AMAZON_M2 import AMAZON_M2
from .BookCrossing import BookCrossing
from .DIGINETICA import DIGINETICA
from .ML1M import ML1M
from .ML10M import ML10M
from .ML25M import ML25M
from .ML100K import ML100K
from .Ciao import Ciao
from .Ciao_PART import Ciao_PART
from .Twitch100K import Twitch100K
from .LFM2B_1MON import LFM2B_1MON